/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Login
         * @description Initiate Google OAuth login flow.
         *
         *     Returns:
         *         Redirect response to Google OAuth authorization URL
         */
        get: operations["login_api_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Callback
         * @description Handle Google OAuth callback.
         *
         *     Args:
         *         response: FastAPI response object
         *         code: Authorization code from Google
         *         state: State parameter for verification
         *         error: Error parameter if OAuth failed
         *
         *     Returns:
         *         Redirect response to frontend dashboard or login page
         */
        get: operations["auth_callback_api_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description Get current authenticated user information.
         *
         *     Args:
         *         request: Current request
         *
         *     Returns:
         *         Current user information
         */
        get: operations["get_current_user_info_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Auth Status
         * @description Check authentication status.
         *
         *     Args:
         *         request: Current request
         *         session_token: Session token from cookie
         *
         *     Returns:
         *         Authentication status and user info if authenticated
         */
        get: operations["get_auth_status_api_auth_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Log out current user.
         *
         *     Args:
         *         response: FastAPI response object
         *         session_token: Session token from cookie
         *
         *     Returns:
         *         Success message
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cleanup Expired Sessions
         * @description Clean up expired sessions (admin endpoint).
         *
         *     Returns:
         *         Cleanup result message
         */
        delete: operations["cleanup_expired_sessions_api_auth_cleanup_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/project-draft/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chat History
         * @description Get chat history for a conversation's project draft.
         */
        get: operations["get_chat_history_api_conversations__conversation_id__project_draft_chat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/project-draft/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream Chat With Project Draft
         * @description Stream chat messages with real-time updates via Server-Sent Events.
         */
        post: operations["stream_chat_with_project_draft_api_conversations__conversation_id__project_draft_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Conversation
         * @description Import a conversation from a share URL and automatically generate a project draft with streaming.
         */
        post: operations["import_conversation_api_conversations_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description Get a paginated list of all imported conversations.
         */
        get: operations["list_conversations_api_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description Get a specific conversation by ID with complete details.
         */
        get: operations["get_conversation_api_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Conversation
         * @description Delete a specific conversation by ID.
         */
        delete: operations["delete_conversation_api_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Conversation
         * @description Update a conversation's title.
         */
        patch: operations["update_conversation_api_conversations__conversation_id__patch"];
        trace?: never;
    };
    "/api/conversations/{conversation_id}/imported_chat_summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation Summary
         * @description Get the current summary for a conversation.
         *
         *     Prefers the imported conversation summary, falls back to chat summary, then to
         *     concatenated imported chat messages if neither exists.
         */
        get: operations["get_conversation_summary_api_conversations__conversation_id__imported_chat_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Conversation Summary
         * @description Update a conversation's summary.
         */
        patch: operations["update_conversation_summary_api_conversations__conversation_id__summary_patch"];
        trace?: never;
    };
    "/api/conversations/import-slack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import From Slack
         * @description Webhook endpoint for importing conversations from Slack.
         */
        post: operations["import_from_slack_api_conversations_import_slack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversation Files
         * @description List all file attachments for a conversation.
         *
         *     Args:
         *         conversation_id: ID of the conversation
         *
         *     Returns:
         *         JSON response with list of file attachments
         *
         *     Raises:
         *         HTTPException: If conversation not found
         */
        get: operations["list_conversation_files_api_conversations__conversation_id__files_get"];
        put?: never;
        /**
         * Upload File
         * @description Upload a file attachment for a conversation.
         *
         *     Args:
         *         conversation_id: ID of the conversation
         *         file: File to upload (multipart/form-data)
         *         llm_model: LLM model to use for processing
         *         llm_provider: LLM provider to use for processing
         *
         *     Returns:
         *         JSON response with file metadata
         *
         *     Raises:
         *         HTTPException: If validation fails or upload fails
         */
        post: operations["upload_file_api_conversations__conversation_id__files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/files/{file_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download File
         * @description Download a file attachment via temporary signed URL.
         *
         *     Args:
         *         file_id: ID of the file attachment
         *
         *     Returns:
         *         Redirect response to S3 signed URL
         *
         *     Raises:
         *         HTTPException: If file not found or download fails
         */
        get: operations["download_file_api_conversations_files__file_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm-defaults/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Llm Providers
         * @description Get all available LLM providers and their supported models.
         */
        get: operations["get_llm_providers_api_llm_defaults_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm-defaults/{prompt_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Llm Defaults
         * @description Get the current default LLM settings for a specific prompt type.
         */
        get: operations["get_llm_defaults_api_llm_defaults__prompt_type__get"];
        /**
         * Update Llm Defaults
         * @description Update the default LLM settings for a specific prompt type.
         */
        put: operations["update_llm_defaults_api_llm_defaults__prompt_type__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm-prompts/{prompt_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Llm Prompt
         * @description Get the active LLM prompt for a given type.
         *     Returns the prompt from database if available, otherwise indicates default is being used.
         */
        get: operations["get_llm_prompt_api_llm_prompts__prompt_type__get"];
        put?: never;
        /**
         * Create Llm Prompt
         * @description Create or update an LLM prompt for a given type.
         *     This will deactivate any existing active prompt of the same type.
         */
        post: operations["create_llm_prompt_api_llm_prompts__prompt_type__post"];
        /**
         * Delete Llm Prompt
         * @description Deactivate the active LLM prompt for a given type.
         *     This will revert to using the default prompt from code.
         */
        delete: operations["delete_llm_prompt_api_llm_prompts__prompt_type__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm-prompts/{prompt_type}/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Default Llm Prompt
         * @description Get the default LLM prompt for a given type.
         *     This always returns the hardcoded default prompt, ignoring any custom prompts.
         */
        get: operations["get_default_llm_prompt_api_llm_prompts__prompt_type__default_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/project-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project Draft
         * @description Get the project draft for a conversation.
         */
        get: operations["get_project_draft_api_conversations__conversation_id__project_draft_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Project Draft
         * @description Manually update a project draft's title and description.
         */
        patch: operations["update_project_draft_api_conversations__conversation_id__project_draft_patch"];
        trace?: never;
    };
    "/api/conversations/{conversation_id}/project-draft/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project Draft Versions
         * @description Get all versions of a project draft for a conversation.
         */
        get: operations["get_project_draft_versions_api_conversations__conversation_id__project_draft_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/project-draft/versions/{version_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate Project Draft Version
         * @description Recover a previous version by creating a new version with the same content.
         */
        post: operations["activate_project_draft_version_api_conversations__conversation_id__project_draft_versions__version_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description Get the Linear project for a conversation.
         */
        get: operations["get_project_api_conversations__conversation_id__project_get"];
        put?: never;
        /**
         * Create Project
         * @description Create a new Linear project for a conversation.
         */
        post: operations["create_project_api_conversations__conversation_id__project_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Get basic API information.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Check API health status.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthStatus
         * @description Authentication status response.
         */
        AuthStatus: {
            /**
             * Authenticated
             * @description Whether the user is authenticated
             */
            authenticated: boolean;
            /** @description User information if authenticated */
            user?: components["schemas"]["AuthUser"] | null;
        };
        /**
         * AuthUser
         * @description User information returned by authentication endpoints.
         */
        AuthUser: {
            /**
             * Id
             * @description Database user ID
             */
            id: number;
            /**
             * Email
             * @description User email address
             */
            email: string;
            /**
             * Name
             * @description User display name
             */
            name: string;
        };
        /** Body_upload_file_api_conversations__conversation_id__files_post */
        Body_upload_file_api_conversations__conversation_id__files_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Llm Model */
            llm_model: string;
            /** Llm Provider */
            llm_provider: string;
        };
        /**
         * ChatHistoryResponse
         * @description Chat history response.
         */
        ChatHistoryResponse: {
            /**
             * Chat Messages
             * @description List of chat messages
             */
            chat_messages: components["schemas"]["ChatMessage"][];
        };
        /**
         * ChatMessage
         * @description Represents a single chat message.
         */
        ChatMessage: {
            /**
             * Role
             * @description Message role ('user' or 'assistant')
             */
            role: string;
            /**
             * Content
             * @description Message content
             */
            content: string;
            /**
             * Sequence Number
             * @description Sequence number for ordering
             */
            sequence_number: number;
            /**
             * Created At
             * @description ISO format creation timestamp
             */
            created_at: string;
            /**
             * Sent By User Id
             * @description ID of the user who sent this message
             */
            sent_by_user_id: number;
            /**
             * Sent By User Name
             * @description Name of the user who sent this message
             */
            sent_by_user_name: string;
            /**
             * Sent By User Email
             * @description Email of the user who sent this message
             */
            sent_by_user_email: string;
            /**
             * Attachments
             * @description File attachments for this message
             */
            attachments?: components["schemas"]["FileAttachment"][];
        };
        /**
         * ChatRequest
         * @description Request model for sending a chat message.
         */
        ChatRequest: {
            /**
             * Message
             * @description User message content
             */
            message: string;
            /**
             * Llm Provider
             * @description LLM provider to use
             */
            llm_provider: string;
            /**
             * Llm Model
             * @description LLM model to use
             */
            llm_model: string;
            /**
             * Attachment Ids
             * @description List of file attachment IDs to include with this message
             */
            attachment_ids?: number[];
        };
        /**
         * ConversationListItem
         * @description Response model for dashboard list view.
         */
        ConversationListItem: {
            /** Id */
            id: number;
            /** Url */
            url: string;
            /** Title */
            title: string;
            /** Import Date */
            import_date: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Is Locked */
            is_locked: boolean;
            /** User Id */
            user_id: number;
            /** User Name */
            user_name: string;
            /** User Email */
            user_email: string;
            /** Project Draft Title */
            project_draft_title?: string | null;
            /** Project Draft Description */
            project_draft_description?: string | null;
            /** Linear Url */
            linear_url?: string | null;
            /** Last User Message Content */
            last_user_message_content?: string | null;
            /** Last Assistant Message Content */
            last_assistant_message_content?: string | null;
        };
        /**
         * ConversationListResponse
         * @description Response for listing conversations.
         */
        ConversationListResponse: {
            /**
             * Conversations
             * @description List of conversations
             */
            conversations: components["schemas"]["ConversationListItem"][];
        };
        /**
         * ConversationResponse
         * @description Response model for conversation API endpoints.
         */
        ConversationResponse: {
            /**
             * Id
             * @description Database ID of the conversation
             */
            id: number;
            /**
             * Url
             * @description Original conversation share URL
             */
            url: string;
            /**
             * Title
             * @description Conversation title
             */
            title: string;
            /**
             * Import Date
             * @description ISO format import timestamp
             */
            import_date: string;
            /**
             * Created At
             * @description ISO format creation timestamp
             */
            created_at: string;
            /**
             * Updated At
             * @description ISO format last update timestamp
             */
            updated_at: string;
            /**
             * Is Locked
             * @description Whether the conversation is locked
             */
            is_locked: boolean;
            /**
             * Has Images
             * @description Whether conversation contains images
             */
            has_images?: boolean | null;
            /**
             * Has Pdfs
             * @description Whether conversation contains PDFs
             */
            has_pdfs?: boolean | null;
            /**
             * User Id
             * @description ID of the user who imported the conversation
             */
            user_id: number;
            /**
             * User Name
             * @description Name of the user who imported the conversation
             */
            user_name: string;
            /**
             * User Email
             * @description Email of the user who imported the conversation
             */
            user_email: string;
            /**
             * Imported Chat
             * @description Conversation messages (optional)
             */
            imported_chat?: components["schemas"]["ImportedChatMessage"][] | null;
        };
        /**
         * ConversationUpdate
         * @description Data required to update a conversation.
         */
        ConversationUpdate: {
            /**
             * Title
             * @description New title for the conversation
             */
            title: string;
        };
        /**
         * ConversationUpdateResponse
         * @description Response for conversation updates.
         */
        ConversationUpdateResponse: {
            /** @description Updated conversation */
            conversation: components["schemas"]["ConversationResponse"];
        };
        /**
         * ErrorResponse
         * @description Standard error response schema.
         */
        ErrorResponse: {
            /**
             * Error
             * @description Error message
             */
            error: string;
            /**
             * Detail
             * @description Additional error details
             */
            detail?: string | null;
        };
        /**
         * FileAttachment
         * @description File attachment model for chat messages.
         */
        FileAttachment: {
            /**
             * Id
             * @description Unique attachment ID
             */
            id: number;
            /**
             * Filename
             * @description Original filename
             */
            filename: string;
            /**
             * File Size
             * @description File size in bytes
             */
            file_size: number;
            /**
             * File Type
             * @description MIME type of the file
             */
            file_type: string;
            /**
             * S3 Key
             * @description S3 storage key
             */
            s3_key: string;
            /**
             * Created At
             * @description ISO format creation timestamp
             */
            created_at: string;
        };
        /**
         * FileListResponse
         * @description File list response.
         */
        FileListResponse: {
            /**
             * Files
             * @description List of file attachments
             */
            files: components["schemas"]["FileAttachment"][];
            /**
             * File Count
             * @description Number of files
             */
            file_count: number;
        };
        /**
         * FileMetadata
         * @description File metadata response.
         */
        FileMetadata: {
            /**
             * Id
             * @description File attachment ID
             */
            id: number;
            /**
             * S3 Key
             * @description S3 storage key
             */
            s3_key: string;
            /**
             * Filename
             * @description Original filename
             */
            filename: string;
            /**
             * File Size
             * @description File size in bytes
             */
            file_size: number;
            /**
             * File Type
             * @description MIME type
             */
            file_type: string;
            /**
             * Conversation Id
             * @description Associated conversation ID
             */
            conversation_id: number;
        };
        /**
         * FileUploadResponse
         * @description File upload response.
         */
        FileUploadResponse: {
            /** @description Uploaded file metadata */
            file: components["schemas"]["FileMetadata"];
            /**
             * Message
             * @description Success message
             */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IdMessageResponse
         * @description Response with ID and message.
         */
        IdMessageResponse: {
            /**
             * Id
             * @description Resource ID
             */
            id: number;
            /**
             * Message
             * @description Response message
             */
            message: string;
        };
        /** ImportChatCreateNew */
        ImportChatCreateNew: {
            /**
             * Url
             * @description Share URL to import (ChatGPT or BranchPrompt)
             */
            url: string;
            /**
             * Llm Model
             * @description LLM model to use
             */
            llm_model: string;
            /**
             * Llm Provider
             * @description LLM provider to use
             */
            llm_provider: string;
            /**
             * Accept Summarization
             * @description Whether to proceed by summarizing when the imported chat exceeds the selected model's context window
             */
            accept_summarization: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            duplicate_resolution: "create_new";
        };
        /** ImportChatPrompt */
        ImportChatPrompt: {
            /**
             * Url
             * @description Share URL to import (ChatGPT or BranchPrompt)
             */
            url: string;
            /**
             * Llm Model
             * @description LLM model to use
             */
            llm_model: string;
            /**
             * Llm Provider
             * @description LLM provider to use
             */
            llm_provider: string;
            /**
             * Accept Summarization
             * @description Whether to proceed by summarizing when the imported chat exceeds the selected model's context window
             */
            accept_summarization: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            duplicate_resolution: "prompt";
        };
        /** ImportChatUpdateExisting */
        ImportChatUpdateExisting: {
            /**
             * Url
             * @description Share URL to import (ChatGPT or BranchPrompt)
             */
            url: string;
            /**
             * Llm Model
             * @description LLM model to use
             */
            llm_model: string;
            /**
             * Llm Provider
             * @description LLM provider to use
             */
            llm_provider: string;
            /**
             * Accept Summarization
             * @description Whether to proceed by summarizing when the imported chat exceeds the selected model's context window
             */
            accept_summarization: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            duplicate_resolution: "update_existing";
            /**
             * Target Conversation Id
             * @description Conversation ID to update when duplicate_resolution is update_existing
             */
            target_conversation_id: number;
        };
        /**
         * ImportedChatMessage
         * @description Represents a single message in a conversation.
         */
        ImportedChatMessage: {
            /**
             * Role
             * @description Message role: 'user' or 'assistant'
             */
            role: string;
            /**
             * Content
             * @description Message content as Markdown
             */
            content: string;
        };
        /**
         * ImportedConversationSummaryUpdate
         * @description Data required to update a conversation summary.
         */
        ImportedConversationSummaryUpdate: {
            /**
             * Summary
             * @description Updated summary text
             */
            summary: string;
        };
        /**
         * LLMDefault
         * @description Model for LLM default settings.
         */
        LLMDefault: {
            /**
             * Llm Provider
             * @description LLM provider name
             */
            llm_provider: string;
            /**
             * Llm Model
             * @description LLM model name
             */
            llm_model: string;
        };
        /**
         * LLMDefaultsResponse
         * @description Response model for getting LLM defaults.
         */
        LLMDefaultsResponse: {
            /** @description Current default LLM settings */
            current_default: components["schemas"]["LLMDefault"];
        };
        /**
         * LLMDefaultsUpdateRequest
         * @description Request model for updating LLM defaults.
         */
        LLMDefaultsUpdateRequest: {
            /**
             * Llm Provider
             * @description LLM provider name
             */
            llm_provider: string;
            /**
             * Llm Model
             * @description LLM model name
             */
            llm_model: string;
        };
        /**
         * LLMDefaultsUpdateResponse
         * @description Response model for updating LLM defaults.
         */
        LLMDefaultsUpdateResponse: {
            /**
             * Message
             * @description Success message
             */
            message: string;
            /** @description The updated default settings */
            updated_default: components["schemas"]["LLMDefault"];
        };
        /**
         * LLMModel
         * @description Model representing an LLM with ID and label.
         */
        LLMModel: {
            /**
             * Id
             * @description Model ID
             */
            id: string;
            /**
             * Provider
             * @description LLM provider name
             */
            provider: string;
            /**
             * Label
             * @description Human-readable model label
             */
            label: string;
            /**
             * Supports Images
             * @description Whether the model supports images
             */
            supports_images: boolean;
            /**
             * Supports Pdfs
             * @description Whether the model supports PDFs
             */
            supports_pdfs: boolean;
            /**
             * Context Window Tokens
             * @description Approximate maximum context window size in tokens
             */
            context_window_tokens: number;
        };
        /**
         * LLMPromptCreateRequest
         * @description Request model for creating a new LLM prompt.
         */
        LLMPromptCreateRequest: {
            /**
             * Prompt Type
             * @description Type of prompt
             */
            prompt_type: string;
            /**
             * System Prompt
             * @description The system prompt text
             */
            system_prompt: string;
        };
        /**
         * LLMPromptDeleteResponse
         * @description Response model for LLM prompt deletion.
         */
        LLMPromptDeleteResponse: {
            /**
             * Message
             * @description Success or error message
             */
            message: string;
        };
        /**
         * LLMPromptResponse
         * @description Response model for LLM prompt operations.
         */
        LLMPromptResponse: {
            /**
             * System Prompt
             * @description The system prompt text
             */
            system_prompt: string;
            /**
             * Is Default
             * @description Whether this is using the default prompt from code
             */
            is_default: boolean;
        };
        /**
         * LLMProvidersResponse
         * @description Response model for getting available LLM providers.
         */
        LLMProvidersResponse: {
            /**
             * Providers
             * @description Available providers and their models
             */
            providers: {
                [key: string]: components["schemas"]["LLMModel"][];
            };
        };
        /**
         * MessageResponse
         * @description Simple message response.
         */
        MessageResponse: {
            /**
             * Message
             * @description Response message
             */
            message: string;
        };
        /**
         * Project
         * @description Represents a Linear project.
         */
        Project: {
            /**
             * Id
             * @description Database project ID
             */
            id: number;
            /**
             * Conversation Id
             * @description Associated conversation ID
             */
            conversation_id: number;
            /**
             * Linear Project Id
             * @description Linear project ID
             */
            linear_project_id: string;
            /**
             * Title
             * @description Project title
             */
            title: string;
            /**
             * Description
             * @description Project description
             */
            description: string;
            /**
             * Linear Url
             * @description Linear project URL
             */
            linear_url: string;
            /**
             * Created At
             * @description ISO format creation timestamp
             */
            created_at: string;
        };
        /**
         * ProjectCreate
         * @description Request model for creating a new project.
         */
        ProjectCreate: {
            /**
             * Title
             * @description Project title
             */
            title: string;
            /**
             * Description
             * @description Project description
             */
            description: string;
        };
        /**
         * ProjectCreateResponse
         * @description Create project response.
         */
        ProjectCreateResponse: {
            /** @description Created project */
            project: components["schemas"]["Project"];
        };
        /**
         * ProjectDraft
         * @description Represents a project draft with its active version.
         */
        ProjectDraft: {
            /**
             * Project Draft Id
             * @description Project draft ID
             */
            project_draft_id: number;
            /**
             * Conversation Id
             * @description Associated conversation ID
             */
            conversation_id: number;
            /** @description Currently active version */
            active_version?: components["schemas"]["ProjectDraftVersion"] | null;
            /**
             * Created At
             * @description ISO format creation timestamp
             */
            created_at: string;
            /**
             * Updated At
             * @description ISO format last update timestamp
             */
            updated_at: string;
        };
        /**
         * ProjectDraftCreateRequest
         * @description Request model for manually creating/updating project draft.
         */
        ProjectDraftCreateRequest: {
            /**
             * Title
             * @description Project title
             */
            title: string;
            /**
             * Description
             * @description Project description
             */
            description: string;
            /**
             * User Prompt
             * @description User prompt that generated this refinement
             */
            user_prompt?: string | null;
        };
        /**
         * ProjectDraftGetResponse
         * @description Get project draft response.
         */
        ProjectDraftGetResponse: {
            /** @description Retrieved project draft */
            project_draft: components["schemas"]["ProjectDraft"];
        };
        /**
         * ProjectDraftUpdateResponse
         * @description Update project draft response.
         */
        ProjectDraftUpdateResponse: {
            /** @description Updated project draft */
            project_draft: components["schemas"]["ProjectDraft"];
        };
        /**
         * ProjectDraftVersion
         * @description Represents a single version of a project draft.
         */
        ProjectDraftVersion: {
            /**
             * Version Id
             * @description Version ID
             */
            version_id: number;
            /**
             * Title
             * @description Project title
             */
            title: string;
            /**
             * Description
             * @description Project description
             */
            description: string;
            /**
             * Is Manual Edit
             * @description Whether this version was manually edited by user
             */
            is_manual_edit: boolean;
            /**
             * Version Number
             * @description Version number for ordering
             */
            version_number: number;
            /**
             * Created At
             * @description ISO format creation timestamp
             */
            created_at: string;
        };
        /**
         * ProjectDraftVersionsResponse
         * @description Get project draft versions response.
         */
        ProjectDraftVersionsResponse: {
            /**
             * Versions
             * @description List of project draft versions
             */
            versions: components["schemas"]["ProjectDraftVersion"][];
        };
        /**
         * ProjectGetResponse
         * @description Get project response.
         */
        ProjectGetResponse: {
            /** @description Retrieved project */
            project: components["schemas"]["Project"];
        };
        /** SearchResponseModel */
        SearchResponseModel: {
            /** Results */
            results: components["schemas"]["SearchResultModel"][];
            stats: components["schemas"]["SearchStatsModel"];
            /** Total Count */
            total_count: number;
            /** Has More */
            has_more: boolean;
        };
        /** SearchResultModel */
        SearchResultModel: {
            /** Id */
            id: number;
            /** Content Type */
            content_type: string;
            /** Content Snippet */
            content_snippet: string;
            /** Score */
            score: number;
            /** Created At */
            created_at: string;
            /** Conversation Id */
            conversation_id: number;
            /** Conversation Title */
            conversation_title: string;
            /** Created By User Name */
            created_by_user_name: string;
            /** Created By User Email */
            created_by_user_email: string;
        };
        /** SearchStatsModel */
        SearchStatsModel: {
            /** Query */
            query: string;
            /** Total Results */
            total_results: number;
            /** Execution Time Ms */
            execution_time_ms: number;
            /** Results By Type */
            results_by_type: {
                [key: string]: number;
            };
        };
        /**
         * SlackImportRequest
         * @description Data sent from Slack for conversation import.
         */
        SlackImportRequest: {
            /**
             * Url
             * @description Share URL to import (ChatGPT or BranchPrompt)
             */
            url: string;
            /**
             * User Id
             * @description ID of user who posted the URL in Slack
             */
            user_id: number;
        };
        /**
         * SummaryResponse
         * @description Response for summary operations.
         */
        SummaryResponse: {
            /**
             * Summary
             * @description Generated or updated summary
             */
            summary: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    auth_callback_api_auth_callback_get: {
        parameters: {
            query: {
                /** @description Authorization code from Google */
                code: string;
                /** @description State parameter for security */
                state?: string;
                /** @description Error from OAuth provider */
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_info_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
        };
    };
    get_auth_status_api_auth_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cleanup_expired_sessions_api_auth_cleanup_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_chat_history_api_conversations__conversation_id__project_draft_chat_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatHistoryResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_chat_with_project_draft_api_conversations__conversation_id__project_draft_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_conversation_api_conversations_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportChatPrompt"] | components["schemas"]["ImportChatCreateNew"] | components["schemas"]["ImportChatUpdateExisting"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_conversations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_conversation_api_conversations__conversation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationUpdateResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_summary_api_conversations__conversation_id__imported_chat_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_conversation_summary_api_conversations__conversation_id__summary_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportedConversationSummaryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_from_slack_api_conversations_import_slack_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlackImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdMessageResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversation_files_api_conversations__conversation_id__files_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileListResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_api_conversations__conversation_id__files_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_api_conversations__conversation_id__files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileUploadResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_file_api_conversations_files__file_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_llm_providers_api_llm_defaults_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMProvidersResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_llm_defaults_api_llm_defaults__prompt_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMDefaultsResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_llm_defaults_api_llm_defaults__prompt_type__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_type: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LLMDefaultsUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMDefaultsUpdateResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_llm_prompt_api_llm_prompts__prompt_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMPromptResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_llm_prompt_api_llm_prompts__prompt_type__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_type: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LLMPromptCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMPromptResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_llm_prompt_api_llm_prompts__prompt_type__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMPromptDeleteResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_default_llm_prompt_api_llm_prompts__prompt_type__default_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMPromptResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_draft_api_conversations__conversation_id__project_draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDraftGetResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_draft_api_conversations__conversation_id__project_draft_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectDraftCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDraftUpdateResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_draft_versions_api_conversations__conversation_id__project_draft_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDraftVersionsResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_project_draft_version_api_conversations__conversation_id__project_draft_versions__version_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDraftUpdateResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_conversations__conversation_id__project_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectGetResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_conversations__conversation_id__project_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectCreateResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                q: string;
                limit: number;
                offset: number;
                status: string;
                sort_by: string;
                sort_dir: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponseModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
