// Re-export autogenerated OpenAPI types to keep a single import path
export type { paths as ApiPaths, components as ApiComponents } from "./api.gen";

// Alias frequently used schemas for convenience
export type ConversationResponse =
  import("./api.gen").components["schemas"]["ConversationResponse"];
export type ConversationListItem =
  import("./api.gen").components["schemas"]["ConversationListItem"];
export type ConversationListResponse =
  import("./api.gen").components["schemas"]["ConversationListResponse"];
export type ConversationUpdateResponse =
  import("./api.gen").components["schemas"]["ConversationUpdateResponse"];
export type ErrorResponse = import("./api.gen").components["schemas"]["ErrorResponse"];
export type MessageResponse = import("./api.gen").components["schemas"]["MessageResponse"];
export type ImportedChatMessage = import("./api.gen").components["schemas"]["ImportedChatMessage"];
export type ChatMessage = import("./api.gen").components["schemas"]["ChatMessage"];
export type ChatRequest = import("./api.gen").components["schemas"]["ChatRequest"];
export type FileAttachment = import("./api.gen").components["schemas"]["FileAttachment"];
export type FileListResponse = import("./api.gen").components["schemas"]["FileListResponse"];
export type FileMetadata = import("./api.gen").components["schemas"]["FileMetadata"];
export type Project = import("./api.gen").components["schemas"]["Project"];
export type ProjectCreateResponse =
  import("./api.gen").components["schemas"]["ProjectCreateResponse"];
export type ProjectGetResponse = import("./api.gen").components["schemas"]["ProjectGetResponse"];
export type ProjectDraft = import("./api.gen").components["schemas"]["ProjectDraft"];
export type ProjectDraftVersion = import("./api.gen").components["schemas"]["ProjectDraftVersion"];
export type ProjectDraftGetResponse =
  import("./api.gen").components["schemas"]["ProjectDraftGetResponse"];
export type ProjectDraftUpdateResponse =
  import("./api.gen").components["schemas"]["ProjectDraftUpdateResponse"];
export type ProjectDraftVersionsCleanResponse =
  import("./api.gen").components["schemas"]["ProjectDraftVersionsResponse"];
export type ProjectDraftCreateRequest =
  import("./api.gen").components["schemas"]["ProjectDraftCreateRequest"];
export type LLMDefault = import("./api.gen").components["schemas"]["LLMDefault"];
export type LLMDefaultsResponse = import("./api.gen").components["schemas"]["LLMDefaultsResponse"];
export type LLMDefaultsUpdateResponse =
  import("./api.gen").components["schemas"]["LLMDefaultsUpdateResponse"];
export type LLMDefaultsUpdateRequest =
  import("./api.gen").components["schemas"]["LLMDefaultsUpdateRequest"];
export type LLMModel = import("./api.gen").components["schemas"]["LLMModel"];
export type LLMProvidersResponse =
  import("./api.gen").components["schemas"]["LLMProvidersResponse"];
export type LLMPromptResponse = import("./api.gen").components["schemas"]["LLMPromptResponse"];
export type LLMPromptDeleteResponse =
  import("./api.gen").components["schemas"]["LLMPromptDeleteResponse"];
export type LLMPromptCreateRequest =
  import("./api.gen").components["schemas"]["LLMPromptCreateRequest"];
// Note: LLMPromptDeleteRequest does not exist in the schema; no alias exported.

// Local-only enums/structures that are not part of the API schema
// ChatStatus is produced via server-sent events; not part of OpenAPI responses
export enum ChatStatus {
  ANALYZING_REQUEST = "analyzing_request",
  EXECUTING_TOOLS = "executing_tools",
  GETTING_PROJECT_DRAFT = "getting_project_draft",
  UPDATING_PROJECT_DRAFT = "updating_project_draft",
  GENERATING_RESPONSE = "generating_response",
  DONE = "done",
}

// Client-only convenience types
export interface ConversationListParams {
  limit?: number;
  offset?: number;
}

export type ConversationDetail = ConversationResponse & { cacheTimestamp?: number };

// Search types still local; keep exporting
export * from "./search";
