"""
Pydantic models for research pipeline run APIs.
"""

from typing import List, Optional

from pydantic import BaseModel, Field

from app.models.conversations import ResearchRunSummary


class ResearchRunInfo(ResearchRunSummary):
    start_deadline_at: Optional[str] = Field(
        None, description="ISO timestamp representing the start deadline window"
    )


class ResearchRunStageProgress(BaseModel):
    stage: str = Field(..., description="Stage identifier")
    iteration: int = Field(..., description="Current iteration number")
    max_iterations: int = Field(..., description="Maximum iterations for the stage")
    progress: float = Field(..., description="Progress percentage (0-1)")
    total_nodes: int = Field(..., description="Total nodes considered so far")
    buggy_nodes: int = Field(..., description="Number of buggy nodes")
    good_nodes: int = Field(..., description="Number of good nodes")
    best_metric: Optional[str] = Field(None, description="Best metric reported at this stage")
    eta_s: Optional[int] = Field(None, description="Estimated time remaining in seconds")
    latest_iteration_time_s: Optional[int] = Field(
        None, description="Duration of the latest iteration in seconds"
    )
    created_at: str = Field(..., description="ISO timestamp when the event was recorded")


class ResearchRunLogEntry(BaseModel):
    id: int = Field(..., description="Unique identifier of the log event")
    level: str = Field(..., description="Log level (info, warn, error, ...)")
    message: str = Field(..., description="Log message")
    created_at: str = Field(..., description="ISO timestamp of the log event")


class ResearchRunNodeEvent(BaseModel):
    id: int = Field(..., description="Unique identifier of the node event")
    stage: str = Field(..., description="Stage identifier")
    node_id: Optional[str] = Field(None, description="Identifier of the node")
    summary: dict = Field(..., description="Summary payload stored in telemetry")
    created_at: str = Field(..., description="ISO timestamp of the event")


class ResearchRunArtifactMetadata(BaseModel):
    id: int = Field(..., description="Artifact identifier")
    artifact_type: str = Field(..., description="Artifact type label")
    filename: str = Field(..., description="Original filename")
    file_size: int = Field(..., description="File size in bytes")
    file_type: str = Field(..., description="MIME type")
    created_at: str = Field(..., description="ISO timestamp when the artifact was recorded")
    download_path: str = Field(..., description="API path to initiate a download")


class ResearchRunDetailsResponse(BaseModel):
    run: ResearchRunInfo = Field(..., description="Metadata describing the run")
    stage_progress: List[ResearchRunStageProgress] = Field(
        default_factory=list, description="Stage progress telemetry"
    )
    logs: List[ResearchRunLogEntry] = Field(
        default_factory=list, description="Log events generated by the run"
    )
    experiment_nodes: List[ResearchRunNodeEvent] = Field(
        default_factory=list, description="Experiment node completion events"
    )
    artifacts: List[ResearchRunArtifactMetadata] = Field(
        default_factory=list, description="Artifacts uploaded for the run"
    )
