import logging
from pathlib import Path
from typing import Any

import open_deep_research.deep_researcher as researcher
from langchain_core.messages import HumanMessage
from langgraph.graph import END, START, StateGraph
from langgraph.graph.state import CompiledStateGraph
from langgraph.runtime import Runtime
from langgraph.types import Checkpointer
from open_deep_research.state import AgentState
from pydantic import BaseModel

from aigraph import utils
from aigraph.agents import research_prompts as prompts

logger = logging.getLogger(__name__)


class State(BaseModel):
    """State for deep research using external API.
    
    Attributes:
        cwd: Working directory (unused internally).
             Passed through but not referenced in node.
        task: Converted to prompt for deep research API.
              _task_to_prompt() formats it as HumanMessage for deep_researcher.
        research: Stores final_report from deep researcher.
                  Accessed via result["final_report"] and passed to baseline.
    """
    # inputs
    cwd: Path
    task: utils.Task

    # generated by `node_research`
    research: AgentState | None = None


async def node_research(state: State, runtime: Runtime) -> dict[str, Any]:
    logger.info("Starting node_research")

    prompt = prompts._task_to_prompt(state.task)
    messages = {"messages": [HumanMessage(content=prompt)]}

    result = await researcher.deep_researcher.ainvoke(
        messages,
        config={"configurable": {"allow_clarification": False}},
    )

    logger.debug(f"deep_research: {result['final_report'][:32]!r}")

    logger.info("Finished node_research")
    return {"research": result}


def build(
    checkpointer: Checkpointer = None,
) -> CompiledStateGraph[State, None, State, State]:
    builder = StateGraph(state_schema=State)

    builder.add_node("node_research", node_research)

    builder.add_edge(START, "node_research")
    builder.add_edge("node_research", END)

    return builder.compile(name="graph_research", checkpointer=checkpointer)  # type: ignore
